### ISSUE TITLE
Can't compile in mac osx 10.9.4

### ISSUE THREAD

**Issue by ericchaves** [cdesiles/node-pcsc#17]
Hi,

I'm trying to use this lib to interact with an ACR 122 usb reader but installation in mac osx 10.9.4 is failing because node-gyp can't find `winscard.h`.

```
npm http 304 https://registry.npmjs.org/bindings

> buffertools@2.1.2 install /Volumes/Macintosh_HD/ericchaves/Projects/nfc/node-pcsclite/node_modules/pcsclite/node_modules/buffertools
> node-gyp rebuild

  CXX(target) Release/obj.target/buffertools/buffertools.o
  SOLINK_MODULE(target) Release/buffertools.node
ld: warning: directory not found for option '-L/usr/local/Cellar/automake/1.12.1/lib'
  SOLINK_MODULE(target) Release/buffertools.node: Finished

> pcsclite@0.3.0 install /Volumes/Macintosh_HD/ericchaves/Projects/nfc/node-pcsclite/node_modules/pcsclite
> node-gyp rebuild

  CXX(target) Release/obj.target/pcsclite/src/addon.o
In file included from ../src/addon.cpp:3:
../src/pcsclite.h:6:10: fatal error: 'winscard.h' file not found
#include <winscard.h>
         ^
1 error generated.
make: *** [Release/obj.target/pcsclite/src/addon.o] Error 1
```

The thing is that headers seems to be present, although I'm not sure if they are where node-gyp expect them to be:

```
hobbes:node-pcsclite ericchaves$ ls /System/Library/Frameworks/PCSC.framework/Headers/
mscdefines.h    musclecard.h    pcsclite.h  winscard.h  wintypes.h
hobbes:node-pcsclite ericchaves$
```

Can someone help me out to properly install it?

Thanks in advance,

Eric

**Comment by LudovicRousseau** [comment]
See https://github.com/LudovicRousseau/node-pcsc/commit/addb0674ef97851ef270b782e86595500d37f635

**Comment by ericchaves** [comment]
Thanks @LudovicRousseau !! That did the trick!
